### ISSUE TITLE
Problems loading krypt-core on OS X Mountain Lion

### ISSUE THREAD

**Issue by tarcieri** [krypt/krypt#33]
On Ruby 2.0.0:

```
╭─tony@vertex  ~ ‹ruby-2.0.0›
╰─$ gem install krypt
Fetching: binyo-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed binyo-0.0.1
Fetching: krypt-provider-openssl-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed krypt-provider-openssl-0.0.1
Fetching: krypt-core-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed krypt-core-0.0.1
Fetching: krypt-0.0.1.gem (100%)
Successfully installed krypt-0.0.1
Parsing documentation for binyo-0.0.1
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/binyo.bundle, skipping
unable to convert "\xF0" from ASCII-8BIT to UTF-8 for lib/binyo.so, skipping
Installing ri documentation for binyo-0.0.1
Parsing documentation for krypt-provider-openssl-0.0.1
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/kryptprovideropenssl.bundle, skipping
unable to convert "\xE8" from ASCII-8BIT to UTF-8 for lib/kryptprovideropenssl.so, skipping
Installing ri documentation for krypt-provider-openssl-0.0.1
Parsing documentation for krypt-core-0.0.1
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/kryptcore.bundle, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for lib/kryptcore.so, skipping
Installing ri documentation for krypt-core-0.0.1
Parsing documentation for krypt-0.0.1
Installing ri documentation for krypt-0.0.1
4 gems installed
╭─tony@vertex  ~ ‹ruby-2.0.0›
╰─$ irb -rkrypt
/Users/tony/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require':LoadError: dlsym(0x7f7fc3b8b650, Init_kryptcore): symbol not found - /Users/tony/.rvm/gems/ruby-2.0.0-p0/gems/krypt-core-0.0.1/lib/kryptcore.bundle
2.0.0p0 :001 >
```

On Ruby 1.9.3:

```
╭─tony@vertex  ~ ‹ruby-1.9.3›
╰─$ gem install krypt
Fetching: binyo-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: krypt-provider-openssl-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: krypt-core-0.0.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: krypt-0.0.1.gem (100%)
Successfully installed binyo-0.0.1
Successfully installed krypt-provider-openssl-0.0.1
Successfully installed krypt-core-0.0.1
Successfully installed krypt-0.0.1
4 gems installed
Installing ri documentation for binyo-0.0.1...
Installing ri documentation for krypt-provider-openssl-0.0.1...
Installing ri documentation for krypt-core-0.0.1...
Installing ri documentation for krypt-0.0.1...
Installing RDoc documentation for binyo-0.0.1...
Installing RDoc documentation for krypt-provider-openssl-0.0.1...
Installing RDoc documentation for krypt-core-0.0.1...
Installing RDoc documentation for krypt-0.0.1...
╭─tony@vertex  ~ ‹ruby-1.9.3›
╰─$ irb -rkrypt
/Users/tony/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':LoadError: dlsym(0x7fd3f964c480, Init_kryptcore): symbol not found - /Users/tony/.rvm/gems/ruby-1.9.3-p392/gems/krypt-core-0.0.1/lib/kryptcore.bundle
1.9.3p392 :001 >
```

**Comment by emboss** [comment]
The 2.0.0 issues look suspiciously like ASCII-8BIT vs. UTF-8 issues that I encountered earlier. I thought those would be fixed, I'll have a look again. But I've never run into the "symbol not found issue" - I will see if I can reproduce it somehow to find out what went wrong there.

**Comment by tarcieri** [comment]
Was able to reproduce this on another machine fairly easily:

```
$ nm /Users/tonyarcieri/.rvm/gems/ruby-1.9.3-p327/gems/krypt-core-0.0.1/lib/kryptcore.bundle
                 U dyld_stub_binder
$ ls -la /Users/tonyarcieri/.rvm/gems/ruby-1.9.3-p327/gems/krypt-core-0.0.1/lib/kryptcore.bundle
-rwxr-xr-x  1 tonyarcieri  tonyarcieri  4348 May 20 10:19 /Users/tonyarcieri/.rvm/gems/ruby-1.9.3-p327/gems/krypt-core-0.0.1/lib/kryptcore.bundle
```

**Comment by tarcieri** [comment]
It seems to be producing a separate .so file:

```
-rwxr-xr-x   1 tonyarcieri  tonyarcieri     4348 May 20 10:19 kryptcore.bundle
-rwxr-xr-x   1 tonyarcieri  tonyarcieri  2636827 May 20 10:19 kryptcore.so
```

**Comment by tarcieri** [comment]
I'm able to build my own gem of krypt-core-c and install it without problems. Perhaps this is already fixed and krypt-core-c just needs a new release?

Note: does this ticket belong on krypt-core-c?
